# Generated by Django 2.1.2 on 2018-10-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181021_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
    ]
