# Generated by Django 2.1 on 2018-10-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181022_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen_mascota',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
